# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rsa_test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rsa_test
  pod 'SwiftyRSA'
  pod 'SwCrypt'

  target 'rsa_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rsa_testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
